/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2014-07-25 03:35:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<title>e-postal services</title>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("   function use()\r\n");
      out.write("   {\r\n");
      out.write("      frm.T1.focus();\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("function check()\r\n");
      out.write("{\r\n");
      out.write("   k=frm.T1.value.length; \r\n");
      out.write("   j= frm.T2.value.length;\r\n");
      out.write("   if( (k <=0 ) || ( j<=0))\r\n");
      out.write("   {\r\n");
      out.write("\t\t if(k<=0)\r\n");
      out.write("\t \t{\r\n");
      out.write("\t\t\talert('Enter  UserName');\r\n");
      out.write("\t\t \tfrm.T1.value=\"\"; \r\n");
      out.write("\t\t\tfrm.T1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\tif(j<=0)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\talert('Enter  Password');\r\n");
      out.write("\t\t\tfrm.T2.value=\"\";\r\n");
      out.write("\t\t\tfrm.T2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t   return true;\r\n");
      out.write("\t\t   }\r\n");
      out.write("   }\r\n");
      out.write("   }\r\n");
      out.write("  </script>\r\n");
      out.write("<BODY background=\"E:\\Project\\background_home.jpg\" onLoad=\"use()\">\r\n");
      out.write("\t<form method=post action=\"adminlogin1.jsp\" name=frm onSubmit=\"return check()\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t <FONT  face=\"comic sans ms\" style=\"font-weight: bold;\" size=3 COLOR=#006600>Admin Login Form</font> </Head>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t\r\n");
      out.write("\t<TABLE cellpadding=\"5\" align=\"center\" border=0 align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td rowspan=\"1\"><FONT  face=\"comic sans ms\" size=\"2\" COLOR=\"#006600\">UserName : </FONT></td>\r\n");
      out.write("\t<td rowspan=\"1\"><input type=text name=\"T1\" size=15 maxlength=15></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td rowspan=\"1\"><FONT  face=\"comic sans ms\" size=\"2\" COLOR=\"#006600\">Password : </font></td>\r\n");
      out.write("\t<td rowspan=\"1\"><input type=\"password\" name=\"T2\" size=15 maxlength=15></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td><input type=\"submit\" value=\"Login\"> </td>\r\n");
      out.write("\t<td><input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("\r\n");
      out.write(" </TABLE>\r\n");
      out.write("<center>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\">Click here for Customer Login : <a href=\"Login.jsp\">Customer Login</a>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
