/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2014-07-29 06:20:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Catalog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>E-Postal Services</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"E:\\Project\\background_home.jpg\">\r\n");
      out.write("\t<h1 style=\"font: bold;\">Stamps</h1>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<form method=\"post\" action=\"clientpurchases.jsp\">\r\n");
      out.write("\t<table border=\"1\" width=\"80\" height=\"100\">\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"E:\\Project\\JawaharlalNehru_stamp.jpg\" name=\"Jawaharlal Nehru\" alt=\"Jawaharlal Nehru\" height=\"200\"/></td>\r\n");
      out.write("\t<td style=\"text-align: left;\" colspan=\"1\"><pre>\r\n");
      out.write("\tStamp: Jawaharlal Nehru \r\n");
      out.write("\tDescription : This is a stamp of Jawaharlal Nehru</pre></td>\r\n");
      out.write("\t<td>Enter quantity : <input type=\"text\" value=\"\" maxlength=\"2\"></td>\r\n");
      out.write("\t<td> Rs.15<br>\r\n");
      out.write("\t<a href=\"clientpurchases.jsp\">Add to Cart</a>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><img src=\"E:\\Project\\MG_stamp.jpg\" name=\"Mahatma Gandhi\" alt=\"Mahatma Gandhi\"/></td>\r\n");
      out.write("\t<td><pre>\r\n");
      out.write("\tStamp: Mahatma Gandhi\r\n");
      out.write("\tDescription : This is a stamp of Mahatma Gandhi</pre></td>\r\n");
      out.write("\t<td>Enter quantity : <input type=\"text\" value=\"\" maxlength=\"2\"></td>\r\n");
      out.write("\t<td> Rs.20 <br>\r\n");
      out.write("\t<a href=\"clientpurchases.jsp\">Add to Cart</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"E:\\Project\\SwamiVivekananda_stamp.jpg\" name=\"Swami Vivekananda\" alt=\"vivekananda\"/></td>\r\n");
      out.write("\t<td><pre>\r\n");
      out.write("\tStamp : Swami Vivekananda\r\n");
      out.write("\tDescription : This is a stamp of Swami Vivekananda</pre></td>\r\n");
      out.write("\t<td>Enter quantity : <input type=\"text\" value=\"\" maxlength=\"2\"></td>\r\n");
      out.write("\t<td> Rs.15<br>\r\n");
      out.write("\t<a href=\"clientpurchases.jsp\">Add to Cart</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img src=\"E:\\Project\\TajMahal_stamp.jpg\" name=\"Taj Mahal\" alt=\"tajmahal\"/></td>\r\n");
      out.write("\t<td><pre>\r\n");
      out.write("\t\tStamp : Taj Mahal\r\n");
      out.write("\t\tDescription : This is a stamp of Taj Mahal</pre></td>\r\n");
      out.write("\t<td>Enter quantity : <input type=\"text\" value=\"\" maxlength=\"2\"></td>\r\n");
      out.write("\t<td> Rs.15<br>\r\n");
      out.write("\t<a href=\"clientpurchases.jsp\">Add to Cart</a>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
