/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2014-08-09 09:09:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class editprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>E-Postal Services</title>\r\n");
      out.write("<script language=\"JavaScript\" >\r\n");
      out.write("function formValidation()  \r\n");
      out.write("        {\r\n");
      out.write("        var fname = document.profile.fname;\r\n");
      out.write("        var lname = document.profile.lname;\r\n");
      out.write("        var email=document.profile.email;\r\n");
      out.write("        var username=document.profile.username;\r\n");
      out.write("        var password = document.profile.password;\r\n");
      out.write("        var role=document.profile.role;\t\r\n");
      out.write("        var gender=document.profile.gender;\r\n");
      out.write("        var day= document.profile.day;\r\n");
      out.write("        var month= document.profile.month;\r\n");
      out.write("        var year= document.profile.year;\r\n");
      out.write("        var addr1=document.profile.addr1;\r\n");
      out.write("        var addr2=document.profile.addr2;\r\n");
      out.write("        var city=document.profile.city;\r\n");
      out.write("        var pincode=document.profile.pincode;\r\n");
      out.write("        var pinreg=new RegExp(\"^[0-9]{6}$\");\r\n");
      out.write("        var pinh=pinreg.exec(pincode.value);\r\n");
      out.write("        var phoneno=document.profile.phoneno;\r\n");
      out.write("        var phreg=new RegExp(\"^[0-9]{10}$\");\r\n");
      out.write("        var rph=phreg.exec(phoneno.value);\r\n");
      out.write("        var accno=document.profile.accno;\r\n");
      out.write("       var accreg=new RegExp(\"^[0-9]{16}$\");\r\n");
      out.write("        var acch=accreg.exec(accno.value);\r\n");
      out.write("        var bankname=document.profile.bankname;\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        if(fname.value==\"\" || fname.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"First Name field is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(allLetter(fname)))  \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"enter valid First Name\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(lname.value==\"\" || lname.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"Last Name field is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(allLetter(lname)))  \r\n");
      out.write("        {  \r\n");
      out.write("        \talert(\"enter valid lname\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(email.value==\"\" || email.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"E-mail field is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("       else if(!(ValidateEmail(email)))  \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"You have entered an invalid email address!\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(username.value==\"\" || username.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"user name is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(allLetter(username)))  \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"enter valid user name\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(password.value==\"\" || password.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"password is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(password_validation(password,6,15)))  \r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"password length should be between 6 and 15\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(role.value==\"\" ||  role.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"role is not selected\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(gender.value==\"\" || gender.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"gender is not selected\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(day.value==\"\" || day.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"day is not selected\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(month.value==\"\" || month.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"month is not selected\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        } \r\n");
      out.write("        else if(year.value==\"\" || year.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"year is not selected\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(datevalidation(day,month,year)))\r\n");
      out.write("        {\r\n");
      out.write("       \t\talert(\"Enter valid DOB\");\r\n");
      out.write("       \t\treturn false;\r\n");
      out.write("       \t}\r\n");
      out.write("        else if(addr1.value==\"\" || addr1.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"address field 1 is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(addr2.value==\"\" || addr2.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"address field 2 is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(city.value==\"\" || city.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"city is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(allLetter(city)))\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"Entered city  is invalid\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(pincode.value==\"\" || pincode.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"pincode field is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("         else if(!pinh) \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"Invalid Pin Number\");    \r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(phoneno.value==\"\" || phoneno.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"phone number is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!rph) \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"Phone number should have only 10 digits\");    \r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("       else if(accno.value==\"\" || accno.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"account number is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!acch) \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"Invalid Account Number\");    \r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("      else if(bankname.value==\"\" || bankname.value==null)\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"bank name is left empty\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        else if(!(allLetter(bankname)))  \r\n");
      out.write("        { \r\n");
      out.write("        \talert(\"enter valid bank name\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        return true;\r\n");
      out.write("        }// formValidation() method closed\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        //method to validate first name should not have numbers\r\n");
      out.write("        function allLetter(a)  \r\n");
      out.write("        {   \r\n");
      out.write("        \tvar letters = /^[A-Za-z]+$/;  \r\n");
      out.write("        \tif(a.value.match(letters))  \r\n");
      out.write("        \t{  \r\n");
      out.write("        \t\treturn true;  \r\n");
      out.write("        \t}  \r\n");
      out.write("        \telse  \r\n");
      out.write("        \t{    \r\n");
      out.write("        \t\treturn false;  \r\n");
      out.write("        \t}  \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         function ValidateEmail(uemail)  \r\n");
      out.write("        {  \r\n");
      out.write("        \tvar emailreg=new RegExp(\"^[a-zA-Z][a-zA-Z0-9_.]*@[a-zA-Z][a-zA-Z0-9_.]*.[a-zA-Z][a-zA-Z0-9_.]{2}.[a-zA-Z][a-zA-Z0-9_.]{2}$|^[a-zA-Z][a-zA-Z0-9_.]*@[a-zA-Z][a-zA-Z0-9_.]*.[a-zA-Z][a-zA-Z0-9_.]{3}$\");\r\n");
      out.write("        \tvar remail=emailreg.exec(uemail.value);\r\n");
      out.write("        \tif(remail)  \r\n");
      out.write("        \t{  \r\n");
      out.write("        \t\treturn true;  \r\n");
      out.write("        \t}  \r\n");
      out.write("        \telse  \r\n");
      out.write("        \t{  \t   \r\n");
      out.write("        \t\t return false;  \r\n");
      out.write("        \t}  \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("        function password_validation(a,b,c)\r\n");
      out.write("        {\r\n");
      out.write("        \tif(a.value.length>=b && a.value.length<=c)\r\n");
      out.write("        \t{\r\n");
      out.write("        \t\treturn true;\r\n");
      out.write("        \t}\r\n");
      out.write("        \telse\r\n");
      out.write("        \t{\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function datevalidation(day,month,year)\r\n");
      out.write("        {\r\n");
      out.write("        \tvar date1 = new Date(year,month,day);\r\n");
      out.write("        \t//var date1=Date.parse(dob);\r\n");
      out.write("        \tvar currdate=new java.util.Date();\r\n");
      out.write("        \t\r\n");
      out.write("        \tif(date1>=currdate())\r\n");
      out.write("       \t\t{\r\n");
      out.write("        \t\talert(\"please enter valid date\");\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("        \telse\r\n");
      out.write("       \t\t{\r\n");
      out.write("        \t\treturn true;\r\n");
      out.write("       \t\t}  \t\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"background_home.jpg\">\r\n");
      out.write("\t<form onSubmit=\"return formValidation();\" action=\"updateprofile.jsp\" method=\"post\" name=\"profile\">\r\n");
      out.write("\t\r\n");
      out.write("<u><h2 align=\"center\" style=\"font-family: inherit;\">Edit Profile</h2></u>\r\n");

	if((String)session.getAttribute("userid")==null)
	{
		response.sendRedirect("catalogloginfail.jsp");
	}

      out.write('	');
      out.write('\r');
      out.write('\n');
	
if((String)session.getAttribute("role")=="Customer")
{

	ResultSet rs=null;
	try
	{		
		String userid=(String)session.getAttribute("userid");
			
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		Connection con=DriverManager.getConnection("jdbc:db2://localhost:50000/POSTALSE","PRATI_000","FCBarcelona10");
		String string="select * from userdetails where username='"+userid+"'";
		PreparedStatement ps=con.prepareStatement(string);
		rs=ps.executeQuery();
		if(rs.next())
		{
	
	

      out.write("\r\n");
      out.write("\t\t<font size=\"4\" face=\"Comic con\">\r\n");
      out.write("\t\t\t<table cellpadding=\"3\" align=\"left\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>First Name : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"fname\" value=\"");
      out.print(rs.getString("fname"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Last Name : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"lname\" value=\"");
      out.print(rs.getString("lname"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Email : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"email\" value=\"");
      out.print(rs.getString("email"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Username : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"username\" value=\"");
      out.print(rs.getString("username"));
      out.write("\" readonly=\"readonly\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Password : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"password\" value=\"");
      out.print(rs.getString("password"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Role : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"role\" value=\"");
      out.print(rs.getString("role"));
      out.write("\" readonly=\"readonly\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Gender : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"gender\" value=\"");
      out.print(rs.getString("gender"));
      out.write("\" readonly=\"readonly\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>DOB : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"day\" value=\"");
      out.print(rs.getString("day"));
      out.write("\" size=\"1\"> / <input type=\"text\" name=\"month\" size=\"9\" value=\"");
      out.print(rs.getString("month"));
      out.write("\"> / <input type=\"text\" size=\"4\" name=\"year\" value=\"");
      out.print(rs.getString("year"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<td>Address Line 1 : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"addr1\" value=\"");
      out.print(rs.getString("addr1"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Address Line 2 : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"addr2\" value=\"");
      out.print(rs.getString("addr2"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>City : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"city\" value=\"");
      out.print(rs.getString("city"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Pincode : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"pincode\" value=\"");
      out.print(rs.getString("pincode"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Phone Number : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"phoneno\" value=\"");
      out.print(rs.getString("phoneno"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Account Number : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"accno\" value=\"");
      out.print(rs.getString("accno"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Bank Name : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"bankname\" value=\"");
      out.print(rs.getString("bankname"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t<tr></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=\"submit\" value=\"Update\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
			
		}
}
catch(SQLException e)
{
	e.printStackTrace();
}
}
else
{
	try
	{		
		String userid=(String)session.getAttribute("userid");
			
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		Connection con=DriverManager.getConnection("jdbc:db2://localhost:50000/POSTALSE","PRATI_000","FCBarcelona10");
		String string="select * from admindetails where username='"+userid+"'";
		PreparedStatement ps=con.prepareStatement(string);
		ResultSet rs=ps.executeQuery();
		if(rs.next())
		{
	
	

      out.write("\r\n");
      out.write("\t\t<font size=\"4\" face=\"Comic con\">\r\n");
      out.write("\t\t\t<table cellpadding=\"3\" align=\"left\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>First Name : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"fname\" value=\"");
      out.print(rs.getString("fname"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Last Name : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"lname\" value=\"");
      out.print(rs.getString("lname"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Username : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"username\" value=\"");
      out.print(rs.getString("username"));
      out.write("\" readonly=\"readonly\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Password : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"password\" value=\"");
      out.print(rs.getString("password"));
      out.write("\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Role : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"role\" value=\"");
      out.print(rs.getString("role"));
      out.write("\" readonly=\"readonly\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=\"submit\" value=\"Update\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
			
		}
	}
	catch(SQLException e)
	{
		e.printStackTrace();
	}
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
