/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2014-08-02 07:26:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import java.io.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("<script language=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function check()\r\n");
      out.write("{\r\n");
      out.write("   k=frm.username.value.length; \r\n");
      out.write("   j= frm.password.value.length;\r\n");
      out.write("   if( (k <=0 ) || ( j<=0))\r\n");
      out.write("   {\r\n");
      out.write("\t\t if(k<=0)\r\n");
      out.write("\t \t{\r\n");
      out.write("\t\t\talert('Enter  UserName');\r\n");
      out.write("\t\t \tfrm.T1.value=\"\"; \r\n");
      out.write("\t\t\tfrm.T1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\tif(j<=0)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\talert('Enter  Password');\r\n");
      out.write("\t\t\tfrm.T2.value=\"\";\r\n");
      out.write("\t\t\tfrm.T2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t   return true;\r\n");
      out.write("\t\t   }\r\n");
      out.write("   }\r\n");
      out.write("   }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"E:\\Project\\background_home.jpg\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form method=\"post\" action=\"Login2.jsp\" onSubmit=\"return check()\">\r\n");
      out.write("\t<center>\r\n");
      out.write("            <table border=\"0\" cellpadding=\"3\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th colspan=\"2\"><FONT  face=\"comic sans ms\" size=3 COLOR=#006600>Customer Login Form</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        \r\n");
      out.write("                        <td><font face=\"comic sans ms\" size=\"2\" COLOR=\"#006600\">UserName :</td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"username\" value=\"\" size=\"15\"/></td>\r\n");
      out.write("                    \t\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><font face=\"comic sans ms\" size=\"2\" COLOR=\"#006600\">Password : </td>\r\n");
      out.write("                        <td><input type=\"password\" name=\"password\" value=\"\" size=\"15\"/></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    \t<td><font face=\"comic sans ms\" size=\"2\" COLOR=\"#006600\">Role : </td>\r\n");
      out.write("                    \t<td><select name=\"role\">\r\n");
      out.write("                    \t<option value=\"customer\">Customer</option>\r\n");
      out.write("                    \t<option value=\"administrator\">Administrator</option>\r\n");
      out.write("                    \t<option value=\"postmaster\">Post Master</option>\r\n");
      out.write("                    \t</select>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><input type=\"submit\" value=\"Login\" /></td>\r\n");
      out.write("                        <td><input type=\"reset\" value=\"Reset\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("           <table>\r\n");
      out.write("           <tr>\r\n");
      out.write("                        <td colspan=\"2\">Yet Not Registered!! <a href=\"Register.jsp\">Register Here</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table>\r\n");
      out.write("                \r\n");
      out.write("                    <tr>\r\n");
      out.write("                    \t<td colspan=\"2\">If you are an Admin, login here : <a href=\"adminlogin.jsp\">Admin Login</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                \r\n");
      out.write("           </table>\r\n");
      out.write("            </center>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
