/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2014-08-08 02:08:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.SQLException;
import java.sql.*;
import java.io.*;

public final class Payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>E-Postal Services</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"background_home.jpg\">\r\n");
      out.write("\t<u><h2 align=\"center\" >Payment Details</h2></u>\r\n");
      out.write("<form action=\"Payment1.jsp\" method=\"post\">\t\t\t\r\n");
 

	try
	{
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		Connection con=DriverManager.getConnection("jdbc:db2://localhost:50000/POSTALSE","PRATI_000","FCBarcelona10");
		
		String str="Select sum(cost) as total from cartitems";
		PreparedStatement ps=con.prepareStatement(str);
		ResultSet rs=ps.executeQuery();
		if(rs.next())
		{
	
			out.println("The total amount to be paid is : "+rs.getString("total"));
		}
	}

	catch(SQLException e)
	{
		e.printStackTrace();
	}
	catch(ClassNotFoundException e)
	{
		e.printStackTrace();
	}

      out.write("\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\t<table  bordercolor=\"white\" width=\"50%\" height=\"80%\" cellpadding=\"4\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Enter the Name as on Card : </td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"cardname\" value=\"\" size=\"30\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Select the type of card : </td>\r\n");
      out.write("\t\t\t<td><select name=\"cardtype\">\r\n");
      out.write("\t\t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t<option value=\"Credit Card\">Credit Card</option>\r\n");
      out.write("\t\t\t<option value=\"Debit Card\">Debit Card</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Enter Debit/Credit Card Number : </td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"cardno\" value=\"\" size=\"30\" ></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Enter the CVV Number : </td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" value=\"\" name=\"cvv\" size=\"8\" maxlength=\"3\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Enter Expiry date of card : </td>\r\n");
      out.write("\t\t\t<td><select name=\"month\">\r\n");
      out.write("\t\t<option value=\"\">Select</option>\r\n");
      out.write("                    \t<option value=\"January\">January</option>\r\n");
      out.write("                    \t<option value=\"February\">February</option>\r\n");
      out.write("                    \t<option value=\"March\">March</option>\r\n");
      out.write("                    \t<option value=\"April\">April</option>\r\n");
      out.write("                    \t<option value=\"May\">May</option>\r\n");
      out.write("                    \t<option value=\"June\">June</option>\r\n");
      out.write("                    \t<option value=\"July\">July</option>\r\n");
      out.write("                    \t<option value=\"August\">August</option>\r\n");
      out.write("                    \t<option value=\"September\">September</option>\r\n");
      out.write("                    \t<option value=\"October\">October</option>\r\n");
      out.write("                    \t<option value=\"November\">November</option>\r\n");
      out.write("                    \t<option value=\"December\">December</option>\r\n");
      out.write("                    \t</select>\r\n");
      out.write("                    \t<select\tname=\"year\">\r\n");
      out.write("\t\t<option value=\"\">Select</option>\r\n");
      out.write("                    \t<option value=\"2013\">2013</option>\r\n");
      out.write("                    \t<option value=\"2014\">2014</option>\r\n");
      out.write("                    \t<option value=\"2015\">2015</option>\r\n");
      out.write("                    \t<option value=\"2016\">2016</option>\r\n");
      out.write("                    \t<option value=\"2017\">2017</option>\r\n");
      out.write("                    \t<option value=\"2018\">2018</option>\r\n");
      out.write("                    \t<option value=\"2019\">2019</option>\r\n");
      out.write("                    \t<option value=\"2020\">2020</option>\r\n");
      out.write("                    \t<option value=\"2021\">2021</option>\r\n");
      out.write("                    \t<option value=\"2022\">2022</option>\r\n");
      out.write("                    \t<option value=\"2023\">2023</option>\r\n");
      out.write("                    \t<option value=\"2024\">2024</option>\r\n");
      out.write("                    \t<option value=\"2025\">2025</option>\r\n");
      out.write("                    \t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\"><input type=\"submit\" value=\"   Proceed To Pay   \" height=\"100%\" width=\"100%\" size=\"100\"></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
